version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: mini_ecommerce_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: mini_ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d mini_ecommerce"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer: # opcional (UI web para DB)
    image: adminer:4
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
