import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SdkProvider } from "@shaayud/sdk-web/provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SdkProvider
        options={{
          host: process.env.NEXT_PUBLIC_API_URL!,
          endpoint: "/identity/ingest",
          autoMouse: { maxMs: 6000, targetFps: 30, sendIntervalMs: 0 },
        }}
      >
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </SdkProvider>
    </html>
  );
}
